name: mightyweb
description: A new Flutter application.
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  #BASE
  nb_utils: ^7.0.3
  google_fonts: ^6.2.1

  #UI
  cached_network_image: ^3.3.1
  flutter_spinkit: ^5.2.1
  package_info_plus: ^8.0.1
  flutter_speed_dial: ^7.0.0
  flutter_native_splash: ^2.4.1

  #STATE MANAGEMENT
  mobx: ^2.3.3+2
  flutter_mobx: ^2.2.1+1

  #STORAGE & PERMISSION
  permission_handler: ^11.3.1
  path_provider: ^2.1.3
  provider: ^6.1.2

  #CONNECTIVITY
  http: ^1.2.2
  share_plus: ^10.0.0
  url_launcher: ^6.3.0
  store_redirect: ^2.0.2

  #Firebase
  firebase_in_app_messaging: ^0.8.0+4
  firebase_messaging: ^15.0.4
  firebase_core: ^3.3.0

  # PUSH NOTIFICATION
  onesignal_flutter: ^5.2.2

  # ADS
  google_mobile_ads: ^5.1.0
  facebook_audience_network: ^1.0.1

  # WEB TOOLS
  flutter_inappwebview: ^6.0.0

  qr_code_scanner: ^1.0.1

  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.11
  mobx_codegen: ^2.6.1
  #flutter packages pub run build_runner build --delete-conflicting-outputs

dependency_overrides:
  js: ^0.6.3
  http: ^1.2.1
  web: ^0.5.0
  nb_utils: 6.1.3

flutter:
  uses-material-design: true
  assets:
    - assets/
    - lang/
